<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => 'Сохранить',
    'Blog' => 'Блог',
    'Content' => 'Содержимое',
    'Created date' => 'Дата создания',
    'Draft' => 'Черновик',
    'Id' => 'Id',
    'Owner' => 'Владелец',
    'Post' => 'Заметка',
    'Posted on {date, date} {date, time}' => 'Опуликовано {date, date} {date, time}',
    'Posts' => 'Заметки',
    'Publish' => 'Опубликовать',
    'Published' => 'Опубликовано',
    'Published date' => 'Дата публикации',
    'Status' => 'Статус',
    'Title' => 'Заголовок',
    'URL slug' => 'URL адрес',
    'Updated date' => 'Дата обновления',
    'by {owner}' => 'от {owner}',
];
